server:
  port: 8001

spring:
  application:
    name: spring-cloud-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/shawnyhw6n9/config-repo/
          search-paths: '{application}'
